### ISSUE TITLE
PButton component, when the "primary" and "loading" configurations are set at the same time, the displayed style is inappropriate

### ISSUE THREAD

**Issue by PrintNow** [HulkApps/polaris-vue#66]
### Current version
`"@hulkapps/polaris-vue": "^2.3.3"`

### PButton component, when the "primary" and "loading" configurations are set at the same time, the displayed style is inappropriate

1. **set "primary"**
![image](https://user-images.githubusercontent.com/28396104/128484571-99ab7916-ef2c-41c5-a607-9dc845b359e7.png)

2. **set "primary" and "loading"**

>  Background-color is inappropriate

![image](https://user-images.githubusercontent.com/28396104/128484879-dd50347e-10ce-4029-9ee7-93ecc4ea8ea3.png)

## Desired effect

Like this, translucent colors based on dominant colors:

```css
.Polaris-Button--primary.Polaris-Button--loading {
  background-color: rgba(0, 123, 92, 0.5);
}
```

![image](https://user-images.githubusercontent.com/28396104/128485133-438422a6-4e12-41dd-a059-8e367d695ba8.png)
